---
##
# Boot is the most important role in this
# pattern.
#
# This describes the project directory structure and
# throws errors when files are not present where expected.
#
- name: Load DNA
  include_vars:
    file: "../../../dna/{{ item }}"
  with_items:
    - "{{ playbook }}.yml"

- debug:
    msg: "{{ playbook }}"
    verbosity: 3

- name: Load playbook variables
  include_vars:
    file: "../../vars_files/playbooks/{{ item }}"
  with_items:
    - "{{ playbook }}.yml"
    - "{{ playbook }}_private.yml"

- name: Load Optional variables
  include_vars:
    file: "../../vars_files/{{ item }}"
  with_items:
    - "prefs/{{whoami}}.yml"
  when: load_prefs

- name: Load DNA variables
  include_vars:
    file: "../../vars_files/{{ item }}"
  with_items:
    - "private/{{provisioner}}.yml"
    - "provisioner/{{provisioner}}/{{distribution}}.yml"
    - "provisioner/{{provisioner}}.yml"
    - "private/{{distribution}}.yml"
    - "distribution/{{distribution}}.yml"